/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * Переменные к шаблону письма
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLetterTemplateVariable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long letterTemplateId;
    private LocalDateTime createDate;
    private String createUser;
    private LocalDateTime lastUpdateDate;
    private String lastUpdateUser;
    private Long variableId;

    public TLetterTemplateVariable() {}

    public TLetterTemplateVariable(TLetterTemplateVariable value) {
        this.id = value.id;
        this.letterTemplateId = value.letterTemplateId;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.lastUpdateDate = value.lastUpdateDate;
        this.lastUpdateUser = value.lastUpdateUser;
        this.variableId = value.variableId;
    }

    public TLetterTemplateVariable(
        Long id,
        Long letterTemplateId,
        LocalDateTime createDate,
        String createUser,
        LocalDateTime lastUpdateDate,
        String lastUpdateUser,
        Long variableId
    ) {
        this.id = id;
        this.letterTemplateId = letterTemplateId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.lastUpdateDate = lastUpdateDate;
        this.lastUpdateUser = lastUpdateUser;
        this.variableId = variableId;
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.id</code>. Первичный
     * ключ
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.id</code>. Первичный
     * ключ
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variable.letter_template_id</code>. Шаблон
     * письма
     */
    public Long getLetterTemplateId() {
        return this.letterTemplateId;
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variable.letter_template_id</code>. Шаблон
     * письма
     */
    public void setLetterTemplateId(Long letterTemplateId) {
        this.letterTemplateId = letterTemplateId;
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.create_date</code>.
     * Дата и время создания
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.create_date</code>.
     * Дата и время создания
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.create_user</code>.
     * Автор создания
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.create_user</code>.
     * Автор создания
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variable.last_update_date</code>. Дата и
     * время изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variable.last_update_date</code>. Дата и
     * время изменения
     */
    public void setLastUpdateDate(LocalDateTime lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variable.last_update_user</code>. Автор
     * изменения
     */
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variable.last_update_user</code>. Автор
     * изменения
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.variable_id</code>.
     * Переменная
     */
    public Long getVariableId() {
        return this.variableId;
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.variable_id</code>.
     * Переменная
     */
    public void setVariableId(Long variableId) {
        this.variableId = variableId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TLetterTemplateVariable other = (TLetterTemplateVariable) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.letterTemplateId == null) {
            if (other.letterTemplateId != null)
                return false;
        }
        else if (!this.letterTemplateId.equals(other.letterTemplateId))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.lastUpdateDate == null) {
            if (other.lastUpdateDate != null)
                return false;
        }
        else if (!this.lastUpdateDate.equals(other.lastUpdateDate))
            return false;
        if (this.lastUpdateUser == null) {
            if (other.lastUpdateUser != null)
                return false;
        }
        else if (!this.lastUpdateUser.equals(other.lastUpdateUser))
            return false;
        if (this.variableId == null) {
            if (other.variableId != null)
                return false;
        }
        else if (!this.variableId.equals(other.variableId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.letterTemplateId == null) ? 0 : this.letterTemplateId.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.lastUpdateDate == null) ? 0 : this.lastUpdateDate.hashCode());
        result = prime * result + ((this.lastUpdateUser == null) ? 0 : this.lastUpdateUser.hashCode());
        result = prime * result + ((this.variableId == null) ? 0 : this.variableId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TLetterTemplateVariable (");

        sb.append(id);
        sb.append(", ").append(letterTemplateId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(lastUpdateDate);
        sb.append(", ").append(lastUpdateUser);
        sb.append(", ").append(variableId);

        sb.append(")");
        return sb.toString();
    }
}
