/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * Переменные к шаблону письма
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLetterTemplateVariables implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long letterTemplateId;
    private String variable;
    private String variableName;
    private LocalDateTime createDate;
    private String createUser;
    private LocalDateTime lastUpdateDate;
    private String lastUpdateUser;

    public TLetterTemplateVariables() {}

    public TLetterTemplateVariables(TLetterTemplateVariables value) {
        this.id = value.id;
        this.letterTemplateId = value.letterTemplateId;
        this.variable = value.variable;
        this.variableName = value.variableName;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.lastUpdateDate = value.lastUpdateDate;
        this.lastUpdateUser = value.lastUpdateUser;
    }

    public TLetterTemplateVariables(
        Long id,
        Long letterTemplateId,
        String variable,
        String variableName,
        LocalDateTime createDate,
        String createUser,
        LocalDateTime lastUpdateDate,
        String lastUpdateUser
    ) {
        this.id = id;
        this.letterTemplateId = letterTemplateId;
        this.variable = variable;
        this.variableName = variableName;
        this.createDate = createDate;
        this.createUser = createUser;
        this.lastUpdateDate = lastUpdateDate;
        this.lastUpdateUser = lastUpdateUser;
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.id</code>. Первичный
     * ключ
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.id</code>. Первичный
     * ключ
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variables.letter_template_id</code>. Шаблон
     * письма
     */
    public Long getLetterTemplateId() {
        return this.letterTemplateId;
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variables.letter_template_id</code>. Шаблон
     * письма
     */
    public void setLetterTemplateId(Long letterTemplateId) {
        this.letterTemplateId = letterTemplateId;
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.variable</code>.
     * Переменная
     */
    public String getVariable() {
        return this.variable;
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.variable</code>.
     * Переменная
     */
    public void setVariable(String variable) {
        this.variable = variable;
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.variable_name</code>.
     * Наименование переменной
     */
    public String getVariableName() {
        return this.variableName;
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.variable_name</code>.
     * Наименование переменной
     */
    public void setVariableName(String variableName) {
        this.variableName = variableName;
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.create_date</code>.
     * Дата и время создания
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.create_date</code>.
     * Дата и время создания
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.create_user</code>.
     * Автор создания
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.create_user</code>.
     * Автор создания
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variables.last_update_date</code>. Дата и
     * время изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variables.last_update_date</code>. Дата и
     * время изменения
     */
    public void setLastUpdateDate(LocalDateTime lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variables.last_update_user</code>. Автор
     * изменения
     */
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variables.last_update_user</code>. Автор
     * изменения
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TLetterTemplateVariables other = (TLetterTemplateVariables) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.letterTemplateId == null) {
            if (other.letterTemplateId != null)
                return false;
        }
        else if (!this.letterTemplateId.equals(other.letterTemplateId))
            return false;
        if (this.variable == null) {
            if (other.variable != null)
                return false;
        }
        else if (!this.variable.equals(other.variable))
            return false;
        if (this.variableName == null) {
            if (other.variableName != null)
                return false;
        }
        else if (!this.variableName.equals(other.variableName))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.lastUpdateDate == null) {
            if (other.lastUpdateDate != null)
                return false;
        }
        else if (!this.lastUpdateDate.equals(other.lastUpdateDate))
            return false;
        if (this.lastUpdateUser == null) {
            if (other.lastUpdateUser != null)
                return false;
        }
        else if (!this.lastUpdateUser.equals(other.lastUpdateUser))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.letterTemplateId == null) ? 0 : this.letterTemplateId.hashCode());
        result = prime * result + ((this.variable == null) ? 0 : this.variable.hashCode());
        result = prime * result + ((this.variableName == null) ? 0 : this.variableName.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.lastUpdateDate == null) ? 0 : this.lastUpdateDate.hashCode());
        result = prime * result + ((this.lastUpdateUser == null) ? 0 : this.lastUpdateUser.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TLetterTemplateVariables (");

        sb.append(id);
        sb.append(", ").append(letterTemplateId);
        sb.append(", ").append(variable);
        sb.append(", ").append(variableName);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(lastUpdateDate);
        sb.append(", ").append(lastUpdateUser);

        sb.append(")");
        return sb.toString();
    }
}
