/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.pojos;


import java.io.Serializable;


/**
 * Вид шаблона (Enum)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLetterTemplateTypeTemplateEnum implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String description;

    public TLetterTemplateTypeTemplateEnum() {}

    public TLetterTemplateTypeTemplateEnum(TLetterTemplateTypeTemplateEnum value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
    }

    public TLetterTemplateTypeTemplateEnum(
        Long id,
        String name,
        String description
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

    /**
     * Getter for <code>admin.t_letter_template_type_template_enum.id</code>. ID
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>admin.t_letter_template_type_template_enum.id</code>. ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>admin.t_letter_template_type_template_enum.name</code>.
     * Наименование
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>admin.t_letter_template_type_template_enum.name</code>.
     * Наименование
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_type_template_enum.description</code>.
     * Описание
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_type_template_enum.description</code>.
     * Описание
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TLetterTemplateTypeTemplateEnum other = (TLetterTemplateTypeTemplateEnum) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TLetterTemplateTypeTemplateEnum (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
