/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * Переменная
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVariable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String description;
    private String defaultVal;
    private LocalDateTime createDate;
    private String createUser;
    private LocalDateTime lastUpdateDate;
    private String lastUpdateUser;

    public TVariable() {}

    public TVariable(TVariable value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.defaultVal = value.defaultVal;
        this.createDate = value.createDate;
        this.createUser = value.createUser;
        this.lastUpdateDate = value.lastUpdateDate;
        this.lastUpdateUser = value.lastUpdateUser;
    }

    public TVariable(
        Long id,
        String name,
        String description,
        String defaultVal,
        LocalDateTime createDate,
        String createUser,
        LocalDateTime lastUpdateDate,
        String lastUpdateUser
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.defaultVal = defaultVal;
        this.createDate = createDate;
        this.createUser = createUser;
        this.lastUpdateDate = lastUpdateDate;
        this.lastUpdateUser = lastUpdateUser;
    }

    /**
     * Getter for <code>admin.t_variable.id</code>. Первичный ключ
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>admin.t_variable.id</code>. Первичный ключ
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>admin.t_variable.name</code>. Наименование
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>admin.t_variable.name</code>. Наименование
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>admin.t_variable.description</code>. Описание
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>admin.t_variable.description</code>. Описание
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>admin.t_variable.default_val</code>. Значение по
     * умолчанию
     */
    public String getDefaultVal() {
        return this.defaultVal;
    }

    /**
     * Setter for <code>admin.t_variable.default_val</code>. Значение по
     * умолчанию
     */
    public void setDefaultVal(String defaultVal) {
        this.defaultVal = defaultVal;
    }

    /**
     * Getter for <code>admin.t_variable.create_date</code>. Дата и время
     * создания
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Setter for <code>admin.t_variable.create_date</code>. Дата и время
     * создания
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * Getter for <code>admin.t_variable.create_user</code>. Автор создания
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * Setter for <code>admin.t_variable.create_user</code>. Автор создания
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * Getter for <code>admin.t_variable.last_update_date</code>. Дата и время
     * изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    /**
     * Setter for <code>admin.t_variable.last_update_date</code>. Дата и время
     * изменения
     */
    public void setLastUpdateDate(LocalDateTime lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * Getter for <code>admin.t_variable.last_update_user</code>. Автор
     * изменения
     */
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }

    /**
     * Setter for <code>admin.t_variable.last_update_user</code>. Автор
     * изменения
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TVariable other = (TVariable) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.defaultVal == null) {
            if (other.defaultVal != null)
                return false;
        }
        else if (!this.defaultVal.equals(other.defaultVal))
            return false;
        if (this.createDate == null) {
            if (other.createDate != null)
                return false;
        }
        else if (!this.createDate.equals(other.createDate))
            return false;
        if (this.createUser == null) {
            if (other.createUser != null)
                return false;
        }
        else if (!this.createUser.equals(other.createUser))
            return false;
        if (this.lastUpdateDate == null) {
            if (other.lastUpdateDate != null)
                return false;
        }
        else if (!this.lastUpdateDate.equals(other.lastUpdateDate))
            return false;
        if (this.lastUpdateUser == null) {
            if (other.lastUpdateUser != null)
                return false;
        }
        else if (!this.lastUpdateUser.equals(other.lastUpdateUser))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.defaultVal == null) ? 0 : this.defaultVal.hashCode());
        result = prime * result + ((this.createDate == null) ? 0 : this.createDate.hashCode());
        result = prime * result + ((this.createUser == null) ? 0 : this.createUser.hashCode());
        result = prime * result + ((this.lastUpdateDate == null) ? 0 : this.lastUpdateDate.hashCode());
        result = prime * result + ((this.lastUpdateUser == null) ? 0 : this.lastUpdateUser.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TVariable (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(defaultVal);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createUser);
        sb.append(", ").append(lastUpdateDate);
        sb.append(", ").append(lastUpdateUser);

        sb.append(")");
        return sb.toString();
    }
}
