logging:
  charset:
    console: UTF-8
  level:
    root: INFO
    org:
      jooq: DEBUG

springdoc:
  swagger-ui:
    path: /public/swagger-ui.html

server:
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:

mirror:
  host:
  endpoint:
    rbac:
    ma:

app:
  config:
    init-params: