logging:
  charset:
    console: UTF-8
  level:
    root: INFO
    org:
      jooq: DEBUG

springdoc:
  swagger-ui:
    path: /public/swagger-ui.html

server:
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    defaultSchema: admin
    baselineOnMigrate: true
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}

mirror:
  endpoint:
    rbac: ${MIRROR_ENDPOINT_RBAC}
    ma: ${MIRROR_ENDPOINT_MA}