/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.AParam;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Ведение параметров приложения
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AParamRecord extends UpdatableRecordImpl<AParamRecord> implements Record8<String, String, String, LocalDateTime, String, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.a_param.key</code>. Первичный ключ
     */
    public void setKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.a_param.key</code>. Первичный ключ
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>admin.a_param.name</code>. Наименование
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.a_param.name</code>. Наименование
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>admin.a_param.val</code>. Значение
     */
    public void setVal(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.a_param.val</code>. Значение
     */
    public String getVal() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin.a_param.create_date</code>. Дата и время создания
     */
    public void setCreateDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.a_param.create_date</code>. Дата и время создания
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>admin.a_param.create_user</code>. Автор создания
     */
    public void setCreateUser(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.a_param.create_user</code>. Автор создания
     */
    public String getCreateUser() {
        return (String) get(4);
    }

    /**
     * Setter for <code>admin.a_param.last_update_date</code>. Дата и время
     * изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.a_param.last_update_date</code>. Дата и время
     * изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>admin.a_param.last_update_user</code>. Автор изменения
     */
    public void setLastUpdateUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>admin.a_param.last_update_user</code>. Автор изменения
     */
    public String getLastUpdateUser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>admin.a_param.default_val</code>. Значение по умолчанию
     */
    public void setDefaultVal(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>admin.a_param.default_val</code>. Значение по умолчанию
     */
    public String getDefaultVal() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, String, LocalDateTime, String, LocalDateTime, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, String, LocalDateTime, String, LocalDateTime, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AParam.A_PARAM.KEY;
    }

    @Override
    public Field<String> field2() {
        return AParam.A_PARAM.NAME;
    }

    @Override
    public Field<String> field3() {
        return AParam.A_PARAM.VAL;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return AParam.A_PARAM.CREATE_DATE;
    }

    @Override
    public Field<String> field5() {
        return AParam.A_PARAM.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return AParam.A_PARAM.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field7() {
        return AParam.A_PARAM.LAST_UPDATE_USER;
    }

    @Override
    public Field<String> field8() {
        return AParam.A_PARAM.DEFAULT_VAL;
    }

    @Override
    public String component1() {
        return getKey();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getVal();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateDate();
    }

    @Override
    public String component5() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component6() {
        return getLastUpdateDate();
    }

    @Override
    public String component7() {
        return getLastUpdateUser();
    }

    @Override
    public String component8() {
        return getDefaultVal();
    }

    @Override
    public String value1() {
        return getKey();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getVal();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateDate();
    }

    @Override
    public String value5() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value6() {
        return getLastUpdateDate();
    }

    @Override
    public String value7() {
        return getLastUpdateUser();
    }

    @Override
    public String value8() {
        return getDefaultVal();
    }

    @Override
    public AParamRecord value1(String value) {
        setKey(value);
        return this;
    }

    @Override
    public AParamRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AParamRecord value3(String value) {
        setVal(value);
        return this;
    }

    @Override
    public AParamRecord value4(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public AParamRecord value5(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public AParamRecord value6(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public AParamRecord value7(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public AParamRecord value8(String value) {
        setDefaultVal(value);
        return this;
    }

    @Override
    public AParamRecord values(String value1, String value2, String value3, LocalDateTime value4, String value5, LocalDateTime value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AParamRecord
     */
    public AParamRecord() {
        super(AParam.A_PARAM);
    }

    /**
     * Create a detached, initialised AParamRecord
     */
    public AParamRecord(String key, String name, String val, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser, String defaultVal) {
        super(AParam.A_PARAM);

        setKey(key);
        setName(name);
        setVal(val);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
        setDefaultVal(defaultVal);
    }
}
