/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TAppControl;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Управление сервисами(заглушка)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAppControlRecord extends UpdatableRecordImpl<TAppControlRecord> implements Record7<String, String, Boolean, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_app_control.name</code>. Наименование
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_app_control.name</code>. Наименование
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>admin.t_app_control.description</code>. Описание
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_app_control.description</code>. Описание
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>admin.t_app_control.enabled</code>. 1 работает в штатном
     * режиме, 0 показывать заглушку
     */
    public void setEnabled(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_app_control.enabled</code>. 1 работает в штатном
     * режиме, 0 показывать заглушку
     */
    public Boolean getEnabled() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>admin.t_app_control.create_date</code>.
     */
    public void setCreateDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_app_control.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>admin.t_app_control.create_user</code>.
     */
    public void setCreateUser(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_app_control.create_user</code>.
     */
    public String getCreateUser() {
        return (String) get(4);
    }

    /**
     * Setter for <code>admin.t_app_control.last_update_date</code>.
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_app_control.last_update_date</code>.
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>admin.t_app_control.last_update_user</code>.
     */
    public void setLastUpdateUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>admin.t_app_control.last_update_user</code>.
     */
    public String getLastUpdateUser() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, Boolean, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, Boolean, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TAppControl.T_APP_CONTROL.NAME;
    }

    @Override
    public Field<String> field2() {
        return TAppControl.T_APP_CONTROL.DESCRIPTION;
    }

    @Override
    public Field<Boolean> field3() {
        return TAppControl.T_APP_CONTROL.ENABLED;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TAppControl.T_APP_CONTROL.CREATE_DATE;
    }

    @Override
    public Field<String> field5() {
        return TAppControl.T_APP_CONTROL.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TAppControl.T_APP_CONTROL.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field7() {
        return TAppControl.T_APP_CONTROL.LAST_UPDATE_USER;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public Boolean component3() {
        return getEnabled();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateDate();
    }

    @Override
    public String component5() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component6() {
        return getLastUpdateDate();
    }

    @Override
    public String component7() {
        return getLastUpdateUser();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public Boolean value3() {
        return getEnabled();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateDate();
    }

    @Override
    public String value5() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value6() {
        return getLastUpdateDate();
    }

    @Override
    public String value7() {
        return getLastUpdateUser();
    }

    @Override
    public TAppControlRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public TAppControlRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TAppControlRecord value3(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public TAppControlRecord value4(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TAppControlRecord value5(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TAppControlRecord value6(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TAppControlRecord value7(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public TAppControlRecord values(String value1, String value2, Boolean value3, LocalDateTime value4, String value5, LocalDateTime value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAppControlRecord
     */
    public TAppControlRecord() {
        super(TAppControl.T_APP_CONTROL);
    }

    /**
     * Create a detached, initialised TAppControlRecord
     */
    public TAppControlRecord(String name, String description, Boolean enabled, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser) {
        super(TAppControl.T_APP_CONTROL);

        setName(name);
        setDescription(description);
        setEnabled(enabled);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
    }
}
