/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TFeedback;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Обратная связь
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFeedbackRecord extends UpdatableRecordImpl<TFeedbackRecord> implements Record8<Integer, String, String, String, LocalDateTime, String, LocalDateTime, byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_feedback.id</code>. ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_feedback.id</code>. ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>admin.t_feedback.fb_theme_name</code>. Имя темы
     */
    public void setFbThemeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_feedback.fb_theme_name</code>. Имя темы
     */
    public String getFbThemeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>admin.t_feedback.feedback_text</code>. Текст обращения
     */
    public void setFeedbackText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_feedback.feedback_text</code>. Текст обращения
     */
    public String getFeedbackText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin.t_feedback.file_attachment</code>. Файл
     */
    public void setFileAttachment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_feedback.file_attachment</code>. Файл
     */
    public String getFileAttachment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>admin.t_feedback.create_date</code>. Дата создания
     * обращения
     */
    public void setCreateDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_feedback.create_date</code>. Дата создания
     * обращения
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>admin.t_feedback.create_user</code>. Автор обращения
     */
    public void setCreateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_feedback.create_user</code>. Автор обращения
     */
    public String getCreateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>admin.t_feedback.last_update_date</code>. Дата и время
     * изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>admin.t_feedback.last_update_date</code>. Дата и время
     * изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>admin.t_feedback.file_store</code>. Хранение файла
     */
    public void setFileStore(byte[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>admin.t_feedback.file_store</code>. Хранение файла
     */
    public byte[] getFileStore() {
        return (byte[]) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, String, LocalDateTime, byte[]> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, String, LocalDateTime, byte[]> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TFeedback.T_FEEDBACK.ID;
    }

    @Override
    public Field<String> field2() {
        return TFeedback.T_FEEDBACK.FB_THEME_NAME;
    }

    @Override
    public Field<String> field3() {
        return TFeedback.T_FEEDBACK.FEEDBACK_TEXT;
    }

    @Override
    public Field<String> field4() {
        return TFeedback.T_FEEDBACK.FILE_ATTACHMENT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TFeedback.T_FEEDBACK.CREATE_DATE;
    }

    @Override
    public Field<String> field6() {
        return TFeedback.T_FEEDBACK.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TFeedback.T_FEEDBACK.LAST_UPDATE_DATE;
    }

    @Override
    public Field<byte[]> field8() {
        return TFeedback.T_FEEDBACK.FILE_STORE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFbThemeName();
    }

    @Override
    public String component3() {
        return getFeedbackText();
    }

    @Override
    public String component4() {
        return getFileAttachment();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateDate();
    }

    @Override
    public String component6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdateDate();
    }

    @Override
    public byte[] component8() {
        return getFileStore();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFbThemeName();
    }

    @Override
    public String value3() {
        return getFeedbackText();
    }

    @Override
    public String value4() {
        return getFileAttachment();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateDate();
    }

    @Override
    public String value6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdateDate();
    }

    @Override
    public byte[] value8() {
        return getFileStore();
    }

    @Override
    public TFeedbackRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TFeedbackRecord value2(String value) {
        setFbThemeName(value);
        return this;
    }

    @Override
    public TFeedbackRecord value3(String value) {
        setFeedbackText(value);
        return this;
    }

    @Override
    public TFeedbackRecord value4(String value) {
        setFileAttachment(value);
        return this;
    }

    @Override
    public TFeedbackRecord value5(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TFeedbackRecord value6(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TFeedbackRecord value7(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TFeedbackRecord value8(byte[] value) {
        setFileStore(value);
        return this;
    }

    @Override
    public TFeedbackRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7, byte[] value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TFeedbackRecord
     */
    public TFeedbackRecord() {
        super(TFeedback.T_FEEDBACK);
    }

    /**
     * Create a detached, initialised TFeedbackRecord
     */
    public TFeedbackRecord(Integer id, String fbThemeName, String feedbackText, String fileAttachment, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, byte[] fileStore) {
        super(TFeedback.T_FEEDBACK);

        setId(id);
        setFbThemeName(fbThemeName);
        setFeedbackText(feedbackText);
        setFileAttachment(fileAttachment);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setFileStore(fileStore);
    }
}
