/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import jooqdata.tables.TFeedbackThemes;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * Справочник тем для обратной связи
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFeedbackThemesRecord extends TableRecordImpl<TFeedbackThemesRecord> implements Record6<Integer, String, LocalDateTime, LocalDateTime, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_feedback_themes.id</code>. ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_feedback_themes.id</code>. ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>admin.t_feedback_themes.fb_theme_name</code>. Имя темы
     */
    public void setFbThemeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_feedback_themes.fb_theme_name</code>. Имя темы
     */
    public String getFbThemeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>admin.t_feedback_themes.create_date</code>. Дата
     * создания темы
     */
    public void setCreateDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_feedback_themes.create_date</code>. Дата
     * создания темы
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>admin.t_feedback_themes.last_update_date</code>. Дата
     * изменения темы
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_feedback_themes.last_update_date</code>. Дата
     * изменения темы
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>admin.t_feedback_themes.create_user</code>. Автор
     * создавший тему
     */
    public void setCreateUser(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_feedback_themes.create_user</code>. Автор
     * создавший тему
     */
    public String getCreateUser() {
        return (String) get(4);
    }

    /**
     * Setter for <code>admin.t_feedback_themes.unique_id</code>. GUID для темы
     */
    public void setUniqueId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_feedback_themes.unique_id</code>. GUID для темы
     */
    public UUID getUniqueId() {
        return (UUID) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, LocalDateTime, LocalDateTime, String, UUID> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, LocalDateTime, LocalDateTime, String, UUID> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TFeedbackThemes.T_FEEDBACK_THEMES.ID;
    }

    @Override
    public Field<String> field2() {
        return TFeedbackThemes.T_FEEDBACK_THEMES.FB_THEME_NAME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TFeedbackThemes.T_FEEDBACK_THEMES.CREATE_DATE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TFeedbackThemes.T_FEEDBACK_THEMES.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field5() {
        return TFeedbackThemes.T_FEEDBACK_THEMES.CREATE_USER;
    }

    @Override
    public Field<UUID> field6() {
        return TFeedbackThemes.T_FEEDBACK_THEMES.UNIQUE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFbThemeName();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdateDate();
    }

    @Override
    public String component5() {
        return getCreateUser();
    }

    @Override
    public UUID component6() {
        return getUniqueId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFbThemeName();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateDate();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdateDate();
    }

    @Override
    public String value5() {
        return getCreateUser();
    }

    @Override
    public UUID value6() {
        return getUniqueId();
    }

    @Override
    public TFeedbackThemesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TFeedbackThemesRecord value2(String value) {
        setFbThemeName(value);
        return this;
    }

    @Override
    public TFeedbackThemesRecord value3(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TFeedbackThemesRecord value4(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TFeedbackThemesRecord value5(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TFeedbackThemesRecord value6(UUID value) {
        setUniqueId(value);
        return this;
    }

    @Override
    public TFeedbackThemesRecord values(Integer value1, String value2, LocalDateTime value3, LocalDateTime value4, String value5, UUID value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TFeedbackThemesRecord
     */
    public TFeedbackThemesRecord() {
        super(TFeedbackThemes.T_FEEDBACK_THEMES);
    }

    /**
     * Create a detached, initialised TFeedbackThemesRecord
     */
    public TFeedbackThemesRecord(Integer id, String fbThemeName, LocalDateTime createDate, LocalDateTime lastUpdateDate, String createUser, UUID uniqueId) {
        super(TFeedbackThemes.T_FEEDBACK_THEMES);

        setId(id);
        setFbThemeName(fbThemeName);
        setCreateDate(createDate);
        setLastUpdateDate(lastUpdateDate);
        setCreateUser(createUser);
        setUniqueId(uniqueId);
    }
}
