/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import jooqdata.tables.TFeedbackFile;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Файлы обратной связи
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TFeedbackFileRecord extends UpdatableRecordImpl<TFeedbackFileRecord> implements Record8<UUID, Long, Long, String, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_feedback_file.uid</code>. UID
     */
    public void setUid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_feedback_file.uid</code>. UID
     */
    public UUID getUid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>admin.t_feedback_file.feedback_id</code>. ID обращения
     */
    public void setFeedbackId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_feedback_file.feedback_id</code>. ID обращения
     */
    public Long getFeedbackId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>admin.t_feedback_file.document_id</code>. ID документа в
     * сервисе документов
     */
    public void setDocumentId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_feedback_file.document_id</code>. ID документа в
     * сервисе документов
     */
    public Long getDocumentId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>admin.t_feedback_file.filename</code>. Название файла
     */
    public void setFilename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_feedback_file.filename</code>. Название файла
     */
    public String getFilename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>admin.t_feedback_file.create_date</code>. Дата и время
     * создания
     */
    public void setCreateDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_feedback_file.create_date</code>. Дата и время
     * создания
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>admin.t_feedback_file.create_user</code>. Автор создания
     */
    public void setCreateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_feedback_file.create_user</code>. Автор создания
     */
    public String getCreateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>admin.t_feedback_file.last_update_date</code>. Дата и
     * время изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>admin.t_feedback_file.last_update_date</code>. Дата и
     * время изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>admin.t_feedback_file.last_update_user</code>. Автор
     * изменения
     */
    public void setLastUpdateUser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>admin.t_feedback_file.last_update_user</code>. Автор
     * изменения
     */
    public String getLastUpdateUser() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, Long, Long, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, Long, Long, String, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return TFeedbackFile.T_FEEDBACK_FILE.UID;
    }

    @Override
    public Field<Long> field2() {
        return TFeedbackFile.T_FEEDBACK_FILE.FEEDBACK_ID;
    }

    @Override
    public Field<Long> field3() {
        return TFeedbackFile.T_FEEDBACK_FILE.DOCUMENT_ID;
    }

    @Override
    public Field<String> field4() {
        return TFeedbackFile.T_FEEDBACK_FILE.FILENAME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TFeedbackFile.T_FEEDBACK_FILE.CREATE_DATE;
    }

    @Override
    public Field<String> field6() {
        return TFeedbackFile.T_FEEDBACK_FILE.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TFeedbackFile.T_FEEDBACK_FILE.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field8() {
        return TFeedbackFile.T_FEEDBACK_FILE.LAST_UPDATE_USER;
    }

    @Override
    public UUID component1() {
        return getUid();
    }

    @Override
    public Long component2() {
        return getFeedbackId();
    }

    @Override
    public Long component3() {
        return getDocumentId();
    }

    @Override
    public String component4() {
        return getFilename();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateDate();
    }

    @Override
    public String component6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdateDate();
    }

    @Override
    public String component8() {
        return getLastUpdateUser();
    }

    @Override
    public UUID value1() {
        return getUid();
    }

    @Override
    public Long value2() {
        return getFeedbackId();
    }

    @Override
    public Long value3() {
        return getDocumentId();
    }

    @Override
    public String value4() {
        return getFilename();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateDate();
    }

    @Override
    public String value6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdateDate();
    }

    @Override
    public String value8() {
        return getLastUpdateUser();
    }

    @Override
    public TFeedbackFileRecord value1(UUID value) {
        setUid(value);
        return this;
    }

    @Override
    public TFeedbackFileRecord value2(Long value) {
        setFeedbackId(value);
        return this;
    }

    @Override
    public TFeedbackFileRecord value3(Long value) {
        setDocumentId(value);
        return this;
    }

    @Override
    public TFeedbackFileRecord value4(String value) {
        setFilename(value);
        return this;
    }

    @Override
    public TFeedbackFileRecord value5(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TFeedbackFileRecord value6(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TFeedbackFileRecord value7(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TFeedbackFileRecord value8(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public TFeedbackFileRecord values(UUID value1, Long value2, Long value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TFeedbackFileRecord
     */
    public TFeedbackFileRecord() {
        super(TFeedbackFile.T_FEEDBACK_FILE);
    }

    /**
     * Create a detached, initialised TFeedbackFileRecord
     */
    public TFeedbackFileRecord(UUID uid, Long feedbackId, Long documentId, String filename, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser) {
        super(TFeedbackFile.T_FEEDBACK_FILE);

        setUid(uid);
        setFeedbackId(feedbackId);
        setDocumentId(documentId);
        setFilename(filename);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
    }
}
