/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TLetterTemplate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Шаблон письма
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLetterTemplateRecord extends UpdatableRecordImpl<TLetterTemplateRecord> implements Record8<Long, String, String, String, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_letter_template.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_letter_template.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>admin.t_letter_template.letter_type</code>. Параметр имя
     */
    public void setLetterType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_letter_template.letter_type</code>. Параметр имя
     */
    public String getLetterType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>admin.t_letter_template.letter_title</code>. Заголовок
     * письма
     */
    public void setLetterTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_letter_template.letter_title</code>. Заголовок
     * письма
     */
    public String getLetterTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin.t_letter_template.letter_sample</code>. Документ
     */
    public void setLetterSample(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_letter_template.letter_sample</code>. Документ
     */
    public String getLetterSample() {
        return (String) get(3);
    }

    /**
     * Setter for <code>admin.t_letter_template.create_date</code>. Дата и время
     * создания
     */
    public void setCreateDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_letter_template.create_date</code>. Дата и время
     * создания
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>admin.t_letter_template.create_user</code>. Автор
     * создания
     */
    public void setCreateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_letter_template.create_user</code>. Автор
     * создания
     */
    public String getCreateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>admin.t_letter_template.last_update_date</code>. Дата и
     * время изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>admin.t_letter_template.last_update_date</code>. Дата и
     * время изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>admin.t_letter_template.last_update_user</code>. Автор
     * изменения
     */
    public void setLastUpdateUser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>admin.t_letter_template.last_update_user</code>. Автор
     * изменения
     */
    public String getLastUpdateUser() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, String, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TLetterTemplate.T_LETTER_TEMPLATE.ID;
    }

    @Override
    public Field<String> field2() {
        return TLetterTemplate.T_LETTER_TEMPLATE.LETTER_TYPE;
    }

    @Override
    public Field<String> field3() {
        return TLetterTemplate.T_LETTER_TEMPLATE.LETTER_TITLE;
    }

    @Override
    public Field<String> field4() {
        return TLetterTemplate.T_LETTER_TEMPLATE.LETTER_SAMPLE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TLetterTemplate.T_LETTER_TEMPLATE.CREATE_DATE;
    }

    @Override
    public Field<String> field6() {
        return TLetterTemplate.T_LETTER_TEMPLATE.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TLetterTemplate.T_LETTER_TEMPLATE.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field8() {
        return TLetterTemplate.T_LETTER_TEMPLATE.LAST_UPDATE_USER;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLetterType();
    }

    @Override
    public String component3() {
        return getLetterTitle();
    }

    @Override
    public String component4() {
        return getLetterSample();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateDate();
    }

    @Override
    public String component6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdateDate();
    }

    @Override
    public String component8() {
        return getLastUpdateUser();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLetterType();
    }

    @Override
    public String value3() {
        return getLetterTitle();
    }

    @Override
    public String value4() {
        return getLetterSample();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateDate();
    }

    @Override
    public String value6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdateDate();
    }

    @Override
    public String value8() {
        return getLastUpdateUser();
    }

    @Override
    public TLetterTemplateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TLetterTemplateRecord value2(String value) {
        setLetterType(value);
        return this;
    }

    @Override
    public TLetterTemplateRecord value3(String value) {
        setLetterTitle(value);
        return this;
    }

    @Override
    public TLetterTemplateRecord value4(String value) {
        setLetterSample(value);
        return this;
    }

    @Override
    public TLetterTemplateRecord value5(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TLetterTemplateRecord value6(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TLetterTemplateRecord value7(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TLetterTemplateRecord value8(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public TLetterTemplateRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLetterTemplateRecord
     */
    public TLetterTemplateRecord() {
        super(TLetterTemplate.T_LETTER_TEMPLATE);
    }

    /**
     * Create a detached, initialised TLetterTemplateRecord
     */
    public TLetterTemplateRecord(Long id, String letterType, String letterTitle, String letterSample, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser) {
        super(TLetterTemplate.T_LETTER_TEMPLATE);

        setId(id);
        setLetterType(letterType);
        setLetterTitle(letterTitle);
        setLetterSample(letterSample);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
    }

    /**
     * Create a detached, initialised TLetterTemplateRecord
     */
    public TLetterTemplateRecord(jooqdata.tables.pojos.TLetterTemplate value) {
        super(TLetterTemplate.T_LETTER_TEMPLATE);

        if (value != null) {
            setId(value.getId());
            setLetterType(value.getLetterType());
            setLetterTitle(value.getLetterTitle());
            setLetterSample(value.getLetterSample());
            setCreateDate(value.getCreateDate());
            setCreateUser(value.getCreateUser());
            setLastUpdateDate(value.getLastUpdateDate());
            setLastUpdateUser(value.getLastUpdateUser());
        }
    }
}
