/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TLetterTemplateVariable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Переменные к шаблону письма
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLetterTemplateVariableRecord extends UpdatableRecordImpl<TLetterTemplateVariableRecord> implements Record9<Long, Long, String, String, LocalDateTime, String, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_letter_template_variable.id</code>. Первичный
     * ключ
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.id</code>. Первичный
     * ключ
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variable.letter_template_id</code>. Шаблон
     * письма
     */
    public void setLetterTemplateId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variable.letter_template_id</code>. Шаблон
     * письма
     */
    public Long getLetterTemplateId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.name</code>.
     * Переменная. Удалить!!!
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.name</code>.
     * Переменная. Удалить!!!
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.val</code>.
     * Наименование переменной. Удалить!!!
     */
    public void setVal(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.val</code>.
     * Наименование переменной. Удалить!!!
     */
    public String getVal() {
        return (String) get(3);
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.create_date</code>.
     * Дата и время создания
     */
    public void setCreateDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.create_date</code>.
     * Дата и время создания
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.create_user</code>.
     * Автор создания
     */
    public void setCreateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.create_user</code>.
     * Автор создания
     */
    public String getCreateUser() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variable.last_update_date</code>. Дата и
     * время изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variable.last_update_date</code>. Дата и
     * время изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variable.last_update_user</code>. Автор
     * изменения
     */
    public void setLastUpdateUser(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variable.last_update_user</code>. Автор
     * изменения
     */
    public String getLastUpdateUser() {
        return (String) get(7);
    }

    /**
     * Setter for <code>admin.t_letter_template_variable.variable_id</code>.
     * Переменная
     */
    public void setVariableId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variable.variable_id</code>.
     * Переменная
     */
    public Long getVariableId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, LocalDateTime, String, LocalDateTime, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, String, String, LocalDateTime, String, LocalDateTime, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.ID;
    }

    @Override
    public Field<Long> field2() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.LETTER_TEMPLATE_ID;
    }

    @Override
    public Field<String> field3() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.NAME;
    }

    @Override
    public Field<String> field4() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.VAL;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.CREATE_DATE;
    }

    @Override
    public Field<String> field6() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field8() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.LAST_UPDATE_USER;
    }

    @Override
    public Field<Long> field9() {
        return TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE.VARIABLE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getLetterTemplateId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getVal();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateDate();
    }

    @Override
    public String component6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdateDate();
    }

    @Override
    public String component8() {
        return getLastUpdateUser();
    }

    @Override
    public Long component9() {
        return getVariableId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getLetterTemplateId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getVal();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateDate();
    }

    @Override
    public String value6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdateDate();
    }

    @Override
    public String value8() {
        return getLastUpdateUser();
    }

    @Override
    public Long value9() {
        return getVariableId();
    }

    @Override
    public TLetterTemplateVariableRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord value2(Long value) {
        setLetterTemplateId(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord value4(String value) {
        setVal(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord value5(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord value6(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord value7(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord value8(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord value9(Long value) {
        setVariableId(value);
        return this;
    }

    @Override
    public TLetterTemplateVariableRecord values(Long value1, Long value2, String value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLetterTemplateVariableRecord
     */
    public TLetterTemplateVariableRecord() {
        super(TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE);
    }

    /**
     * Create a detached, initialised TLetterTemplateVariableRecord
     */
    public TLetterTemplateVariableRecord(Long id, Long letterTemplateId, String name, String val, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser, Long variableId) {
        super(TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE);

        setId(id);
        setLetterTemplateId(letterTemplateId);
        setName(name);
        setVal(val);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
        setVariableId(variableId);
    }

    /**
     * Create a detached, initialised TLetterTemplateVariableRecord
     */
    public TLetterTemplateVariableRecord(jooqdata.tables.pojos.TLetterTemplateVariable value) {
        super(TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE);

        if (value != null) {
            setId(value.getId());
            setLetterTemplateId(value.getLetterTemplateId());
            setName(value.getName());
            setVal(value.getVal());
            setCreateDate(value.getCreateDate());
            setCreateUser(value.getCreateUser());
            setLastUpdateDate(value.getLastUpdateDate());
            setLastUpdateUser(value.getLastUpdateUser());
            setVariableId(value.getVariableId());
        }
    }
}
