/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TLetterTemplateVariables;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Переменные к шаблону письма
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLetterTemplateVariablesRecord extends UpdatableRecordImpl<TLetterTemplateVariablesRecord> implements Record8<Long, Long, String, String, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_letter_template_variables.id</code>. Первичный
     * ключ
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.id</code>. Первичный
     * ключ
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variables.letter_template_id</code>. Шаблон
     * письма
     */
    public void setLetterTemplateId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variables.letter_template_id</code>. Шаблон
     * письма
     */
    public Long getLetterTemplateId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.variable</code>.
     * Переменная
     */
    public void setVariable(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.variable</code>.
     * Переменная
     */
    public String getVariable() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.variable_name</code>.
     * Наименование переменной
     */
    public void setVariableName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.variable_name</code>.
     * Наименование переменной
     */
    public String getVariableName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.create_date</code>.
     * Дата и время создания
     */
    public void setCreateDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.create_date</code>.
     * Дата и время создания
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>admin.t_letter_template_variables.create_user</code>.
     * Автор создания
     */
    public void setCreateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_variables.create_user</code>.
     * Автор создания
     */
    public String getCreateUser() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variables.last_update_date</code>. Дата и
     * время изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variables.last_update_date</code>. Дата и
     * время изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_variables.last_update_user</code>. Автор
     * изменения
     */
    public void setLastUpdateUser(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_variables.last_update_user</code>. Автор
     * изменения
     */
    public String getLastUpdateUser() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, String, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, String, String, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES.ID;
    }

    @Override
    public Field<Long> field2() {
        return TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES.LETTER_TEMPLATE_ID;
    }

    @Override
    public Field<String> field3() {
        return TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES.VARIABLE;
    }

    @Override
    public Field<String> field4() {
        return TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES.VARIABLE_NAME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES.CREATE_DATE;
    }

    @Override
    public Field<String> field6() {
        return TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field8() {
        return TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES.LAST_UPDATE_USER;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getLetterTemplateId();
    }

    @Override
    public String component3() {
        return getVariable();
    }

    @Override
    public String component4() {
        return getVariableName();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateDate();
    }

    @Override
    public String component6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdateDate();
    }

    @Override
    public String component8() {
        return getLastUpdateUser();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getLetterTemplateId();
    }

    @Override
    public String value3() {
        return getVariable();
    }

    @Override
    public String value4() {
        return getVariableName();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateDate();
    }

    @Override
    public String value6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdateDate();
    }

    @Override
    public String value8() {
        return getLastUpdateUser();
    }

    @Override
    public TLetterTemplateVariablesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TLetterTemplateVariablesRecord value2(Long value) {
        setLetterTemplateId(value);
        return this;
    }

    @Override
    public TLetterTemplateVariablesRecord value3(String value) {
        setVariable(value);
        return this;
    }

    @Override
    public TLetterTemplateVariablesRecord value4(String value) {
        setVariableName(value);
        return this;
    }

    @Override
    public TLetterTemplateVariablesRecord value5(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TLetterTemplateVariablesRecord value6(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TLetterTemplateVariablesRecord value7(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TLetterTemplateVariablesRecord value8(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public TLetterTemplateVariablesRecord values(Long value1, Long value2, String value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLetterTemplateVariablesRecord
     */
    public TLetterTemplateVariablesRecord() {
        super(TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES);
    }

    /**
     * Create a detached, initialised TLetterTemplateVariablesRecord
     */
    public TLetterTemplateVariablesRecord(Long id, Long letterTemplateId, String variable, String variableName, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser) {
        super(TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES);

        setId(id);
        setLetterTemplateId(letterTemplateId);
        setVariable(variable);
        setVariableName(variableName);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
    }

    /**
     * Create a detached, initialised TLetterTemplateVariablesRecord
     */
    public TLetterTemplateVariablesRecord(jooqdata.tables.pojos.TLetterTemplateVariables value) {
        super(TLetterTemplateVariables.T_LETTER_TEMPLATE_VARIABLES);

        if (value != null) {
            setId(value.getId());
            setLetterTemplateId(value.getLetterTemplateId());
            setVariable(value.getVariable());
            setVariableName(value.getVariableName());
            setCreateDate(value.getCreateDate());
            setCreateUser(value.getCreateUser());
            setLastUpdateDate(value.getLastUpdateDate());
            setLastUpdateUser(value.getLastUpdateUser());
        }
    }
}
