/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.TLetterTemplateTypeTemplateEnum;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Вид шаблона (Enum)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLetterTemplateTypeTemplateEnumRecord extends UpdatableRecordImpl<TLetterTemplateTypeTemplateEnumRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_letter_template_type_template_enum.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_type_template_enum.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>admin.t_letter_template_type_template_enum.name</code>.
     * Наименование
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_letter_template_type_template_enum.name</code>.
     * Наименование
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>admin.t_letter_template_type_template_enum.description</code>.
     * Описание
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>admin.t_letter_template_type_template_enum.description</code>.
     * Описание
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TLetterTemplateTypeTemplateEnum.T_LETTER_TEMPLATE_TYPE_TEMPLATE_ENUM.ID;
    }

    @Override
    public Field<String> field2() {
        return TLetterTemplateTypeTemplateEnum.T_LETTER_TEMPLATE_TYPE_TEMPLATE_ENUM.NAME;
    }

    @Override
    public Field<String> field3() {
        return TLetterTemplateTypeTemplateEnum.T_LETTER_TEMPLATE_TYPE_TEMPLATE_ENUM.DESCRIPTION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public TLetterTemplateTypeTemplateEnumRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TLetterTemplateTypeTemplateEnumRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TLetterTemplateTypeTemplateEnumRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TLetterTemplateTypeTemplateEnumRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLetterTemplateTypeTemplateEnumRecord
     */
    public TLetterTemplateTypeTemplateEnumRecord() {
        super(TLetterTemplateTypeTemplateEnum.T_LETTER_TEMPLATE_TYPE_TEMPLATE_ENUM);
    }

    /**
     * Create a detached, initialised TLetterTemplateTypeTemplateEnumRecord
     */
    public TLetterTemplateTypeTemplateEnumRecord(Long id, String name, String description) {
        super(TLetterTemplateTypeTemplateEnum.T_LETTER_TEMPLATE_TYPE_TEMPLATE_ENUM);

        setId(id);
        setName(name);
        setDescription(description);
    }
}
