/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TMatrix;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Настройка матрицы Компания организатор / Организатор &lt;&gt; Заказчик /
 * Инициатор"
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMatrixRecord extends UpdatableRecordImpl<TMatrixRecord> implements Record10<Long, String, String, String, String, LocalDateTime, String, LocalDateTime, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_matrix.id</code>. Первичный ключ
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_matrix.id</code>. Первичный ключ
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>admin.t_matrix.company_code</code>. Код компании
     * организатора
     */
    public void setCompanyCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_matrix.company_code</code>. Код компании
     * организатора
     */
    public String getCompanyCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>admin.t_matrix.org_code</code>. Код организатора
     */
    public void setOrgCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_matrix.org_code</code>. Код организатора
     */
    public String getOrgCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin.t_matrix.customer_code</code>. Код заказчика
     */
    public void setCustomerCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_matrix.customer_code</code>. Код заказчика
     */
    public String getCustomerCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>admin.t_matrix.initiator_code</code>. Код инициатора
     */
    public void setInitiatorCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_matrix.initiator_code</code>. Код инициатора
     */
    public String getInitiatorCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>admin.t_matrix.create_date</code>. Дата и время создания
     */
    public void setCreateDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_matrix.create_date</code>. Дата и время создания
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>admin.t_matrix.create_user</code>. Автор создания
     */
    public void setCreateUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>admin.t_matrix.create_user</code>. Автор создания
     */
    public String getCreateUser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>admin.t_matrix.last_update_date</code>. Дата и время
     * изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>admin.t_matrix.last_update_date</code>. Дата и время
     * изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>admin.t_matrix.last_update_user</code>. Автор изменения
     */
    public void setLastUpdateUser(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>admin.t_matrix.last_update_user</code>. Автор изменения
     */
    public String getLastUpdateUser() {
        return (String) get(8);
    }

    /**
     * Setter for <code>admin.t_matrix.is_deleted</code>. Статус удаления
     */
    public void setIsDeleted(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>admin.t_matrix.is_deleted</code>. Статус удаления
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, String, LocalDateTime, String, LocalDateTime, String, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, String, String, LocalDateTime, String, LocalDateTime, String, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TMatrix.T_MATRIX.ID;
    }

    @Override
    public Field<String> field2() {
        return TMatrix.T_MATRIX.COMPANY_CODE;
    }

    @Override
    public Field<String> field3() {
        return TMatrix.T_MATRIX.ORG_CODE;
    }

    @Override
    public Field<String> field4() {
        return TMatrix.T_MATRIX.CUSTOMER_CODE;
    }

    @Override
    public Field<String> field5() {
        return TMatrix.T_MATRIX.INITIATOR_CODE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TMatrix.T_MATRIX.CREATE_DATE;
    }

    @Override
    public Field<String> field7() {
        return TMatrix.T_MATRIX.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TMatrix.T_MATRIX.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field9() {
        return TMatrix.T_MATRIX.LAST_UPDATE_USER;
    }

    @Override
    public Field<Boolean> field10() {
        return TMatrix.T_MATRIX.IS_DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCompanyCode();
    }

    @Override
    public String component3() {
        return getOrgCode();
    }

    @Override
    public String component4() {
        return getCustomerCode();
    }

    @Override
    public String component5() {
        return getInitiatorCode();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateDate();
    }

    @Override
    public String component7() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component8() {
        return getLastUpdateDate();
    }

    @Override
    public String component9() {
        return getLastUpdateUser();
    }

    @Override
    public Boolean component10() {
        return getIsDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCompanyCode();
    }

    @Override
    public String value3() {
        return getOrgCode();
    }

    @Override
    public String value4() {
        return getCustomerCode();
    }

    @Override
    public String value5() {
        return getInitiatorCode();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateDate();
    }

    @Override
    public String value7() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value8() {
        return getLastUpdateDate();
    }

    @Override
    public String value9() {
        return getLastUpdateUser();
    }

    @Override
    public Boolean value10() {
        return getIsDeleted();
    }

    @Override
    public TMatrixRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TMatrixRecord value2(String value) {
        setCompanyCode(value);
        return this;
    }

    @Override
    public TMatrixRecord value3(String value) {
        setOrgCode(value);
        return this;
    }

    @Override
    public TMatrixRecord value4(String value) {
        setCustomerCode(value);
        return this;
    }

    @Override
    public TMatrixRecord value5(String value) {
        setInitiatorCode(value);
        return this;
    }

    @Override
    public TMatrixRecord value6(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TMatrixRecord value7(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TMatrixRecord value8(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TMatrixRecord value9(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public TMatrixRecord value10(Boolean value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public TMatrixRecord values(Long value1, String value2, String value3, String value4, String value5, LocalDateTime value6, String value7, LocalDateTime value8, String value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TMatrixRecord
     */
    public TMatrixRecord() {
        super(TMatrix.T_MATRIX);
    }

    /**
     * Create a detached, initialised TMatrixRecord
     */
    public TMatrixRecord(Long id, String companyCode, String orgCode, String customerCode, String initiatorCode, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser, Boolean isDeleted) {
        super(TMatrix.T_MATRIX);

        setId(id);
        setCompanyCode(companyCode);
        setOrgCode(orgCode);
        setCustomerCode(customerCode);
        setInitiatorCode(initiatorCode);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
        setIsDeleted(isDeleted);
    }
}
