/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TServiceOfferType;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Вид шаблона КП для услуги
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TServiceOfferTypeRecord extends UpdatableRecordImpl<TServiceOfferTypeRecord> implements Record8<Long, String, String, LocalDateTime, String, LocalDateTime, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_service_offer_type.id</code>. Первичный ключ
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_service_offer_type.id</code>. Первичный ключ
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>admin.t_service_offer_type.service_code</code>. Код
     * услуги
     */
    public void setServiceCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_service_offer_type.service_code</code>. Код
     * услуги
     */
    public String getServiceCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>admin.t_service_offer_type.offer_type</code>. Вид
     * шаблона КП
     */
    public void setOfferType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_service_offer_type.offer_type</code>. Вид
     * шаблона КП
     */
    public String getOfferType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin.t_service_offer_type.create_date</code>. Дата
     * создания
     */
    public void setCreateDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_service_offer_type.create_date</code>. Дата
     * создания
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>admin.t_service_offer_type.create_user</code>. Автор
     * создания
     */
    public void setCreateUser(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_service_offer_type.create_user</code>. Автор
     * создания
     */
    public String getCreateUser() {
        return (String) get(4);
    }

    /**
     * Setter for <code>admin.t_service_offer_type.last_update_date</code>. Дата
     * и время изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_service_offer_type.last_update_date</code>. Дата
     * и время изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>admin.t_service_offer_type.last_update_user</code>.
     * Автор изменения
     */
    public void setLastUpdateUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>admin.t_service_offer_type.last_update_user</code>.
     * Автор изменения
     */
    public String getLastUpdateUser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>admin.t_service_offer_type.with_costing_default</code>.
     * Запросить расшифровку (по умолчанию)
     */
    public void setWithCostingDefault(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>admin.t_service_offer_type.with_costing_default</code>.
     * Запросить расшифровку (по умолчанию)
     */
    public Boolean getWithCostingDefault() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, LocalDateTime, String, LocalDateTime, String, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, LocalDateTime, String, LocalDateTime, String, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TServiceOfferType.T_SERVICE_OFFER_TYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return TServiceOfferType.T_SERVICE_OFFER_TYPE.SERVICE_CODE;
    }

    @Override
    public Field<String> field3() {
        return TServiceOfferType.T_SERVICE_OFFER_TYPE.OFFER_TYPE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TServiceOfferType.T_SERVICE_OFFER_TYPE.CREATE_DATE;
    }

    @Override
    public Field<String> field5() {
        return TServiceOfferType.T_SERVICE_OFFER_TYPE.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TServiceOfferType.T_SERVICE_OFFER_TYPE.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field7() {
        return TServiceOfferType.T_SERVICE_OFFER_TYPE.LAST_UPDATE_USER;
    }

    @Override
    public Field<Boolean> field8() {
        return TServiceOfferType.T_SERVICE_OFFER_TYPE.WITH_COSTING_DEFAULT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getServiceCode();
    }

    @Override
    public String component3() {
        return getOfferType();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateDate();
    }

    @Override
    public String component5() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component6() {
        return getLastUpdateDate();
    }

    @Override
    public String component7() {
        return getLastUpdateUser();
    }

    @Override
    public Boolean component8() {
        return getWithCostingDefault();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getServiceCode();
    }

    @Override
    public String value3() {
        return getOfferType();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateDate();
    }

    @Override
    public String value5() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value6() {
        return getLastUpdateDate();
    }

    @Override
    public String value7() {
        return getLastUpdateUser();
    }

    @Override
    public Boolean value8() {
        return getWithCostingDefault();
    }

    @Override
    public TServiceOfferTypeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TServiceOfferTypeRecord value2(String value) {
        setServiceCode(value);
        return this;
    }

    @Override
    public TServiceOfferTypeRecord value3(String value) {
        setOfferType(value);
        return this;
    }

    @Override
    public TServiceOfferTypeRecord value4(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TServiceOfferTypeRecord value5(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TServiceOfferTypeRecord value6(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TServiceOfferTypeRecord value7(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public TServiceOfferTypeRecord value8(Boolean value) {
        setWithCostingDefault(value);
        return this;
    }

    @Override
    public TServiceOfferTypeRecord values(Long value1, String value2, String value3, LocalDateTime value4, String value5, LocalDateTime value6, String value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TServiceOfferTypeRecord
     */
    public TServiceOfferTypeRecord() {
        super(TServiceOfferType.T_SERVICE_OFFER_TYPE);
    }

    /**
     * Create a detached, initialised TServiceOfferTypeRecord
     */
    public TServiceOfferTypeRecord(Long id, String serviceCode, String offerType, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser, Boolean withCostingDefault) {
        super(TServiceOfferType.T_SERVICE_OFFER_TYPE);

        setId(id);
        setServiceCode(serviceCode);
        setOfferType(offerType);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
        setWithCostingDefault(withCostingDefault);
    }
}
