/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TVariable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Переменная
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TVariableRecord extends UpdatableRecordImpl<TVariableRecord> implements Record8<Long, String, String, String, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin.t_variable.id</code>. Первичный ключ
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>admin.t_variable.id</code>. Первичный ключ
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>admin.t_variable.name</code>. Наименование
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>admin.t_variable.name</code>. Наименование
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>admin.t_variable.description</code>. Описание
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>admin.t_variable.description</code>. Описание
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin.t_variable.default_val</code>. Значение по
     * умолчанию
     */
    public void setDefaultVal(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>admin.t_variable.default_val</code>. Значение по
     * умолчанию
     */
    public String getDefaultVal() {
        return (String) get(3);
    }

    /**
     * Setter for <code>admin.t_variable.create_date</code>. Дата и время
     * создания
     */
    public void setCreateDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>admin.t_variable.create_date</code>. Дата и время
     * создания
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>admin.t_variable.create_user</code>. Автор создания
     */
    public void setCreateUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>admin.t_variable.create_user</code>. Автор создания
     */
    public String getCreateUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>admin.t_variable.last_update_date</code>. Дата и время
     * изменения
     */
    public void setLastUpdateDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>admin.t_variable.last_update_date</code>. Дата и время
     * изменения
     */
    public LocalDateTime getLastUpdateDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>admin.t_variable.last_update_user</code>. Автор
     * изменения
     */
    public void setLastUpdateUser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>admin.t_variable.last_update_user</code>. Автор
     * изменения
     */
    public String getLastUpdateUser() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, String, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TVariable.T_VARIABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return TVariable.T_VARIABLE.NAME;
    }

    @Override
    public Field<String> field3() {
        return TVariable.T_VARIABLE.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return TVariable.T_VARIABLE.DEFAULT_VAL;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TVariable.T_VARIABLE.CREATE_DATE;
    }

    @Override
    public Field<String> field6() {
        return TVariable.T_VARIABLE.CREATE_USER;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TVariable.T_VARIABLE.LAST_UPDATE_DATE;
    }

    @Override
    public Field<String> field8() {
        return TVariable.T_VARIABLE.LAST_UPDATE_USER;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getDefaultVal();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateDate();
    }

    @Override
    public String component6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdateDate();
    }

    @Override
    public String component8() {
        return getLastUpdateUser();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getDefaultVal();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateDate();
    }

    @Override
    public String value6() {
        return getCreateUser();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdateDate();
    }

    @Override
    public String value8() {
        return getLastUpdateUser();
    }

    @Override
    public TVariableRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TVariableRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TVariableRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TVariableRecord value4(String value) {
        setDefaultVal(value);
        return this;
    }

    @Override
    public TVariableRecord value5(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TVariableRecord value6(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public TVariableRecord value7(LocalDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    public TVariableRecord value8(String value) {
        setLastUpdateUser(value);
        return this;
    }

    @Override
    public TVariableRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TVariableRecord
     */
    public TVariableRecord() {
        super(TVariable.T_VARIABLE);
    }

    /**
     * Create a detached, initialised TVariableRecord
     */
    public TVariableRecord(Long id, String name, String description, String defaultVal, LocalDateTime createDate, String createUser, LocalDateTime lastUpdateDate, String lastUpdateUser) {
        super(TVariable.T_VARIABLE);

        setId(id);
        setName(name);
        setDescription(description);
        setDefaultVal(defaultVal);
        setCreateDate(createDate);
        setCreateUser(createUser);
        setLastUpdateDate(lastUpdateDate);
        setLastUpdateUser(lastUpdateUser);
    }
}
