/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import jooqdata.Admin;
import jooqdata.Keys;
import jooqdata.tables.records.TFaqQuestionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * FAQ: вопросы
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TFaqQuestion extends TableImpl<TFaqQuestionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>admin.t_faq_question</code>
     */
    public static final TFaqQuestion T_FAQ_QUESTION = new TFaqQuestion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TFaqQuestionRecord> getRecordType() {
        return TFaqQuestionRecord.class;
    }

    /**
     * The column <code>admin.t_faq_question.id</code>. Первичный ключ
     */
    public final TableField<TFaqQuestionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("admin.get_id()", SQLDataType.BIGINT)), this, "Первичный ключ");

    /**
     * The column <code>admin.t_faq_question.service_name</code>. Наименование
     * сервиса
     */
    public final TableField<TFaqQuestionRecord, String> SERVICE_NAME = createField(DSL.name("service_name"), SQLDataType.VARCHAR.nullable(false), this, "Наименование сервиса");

    /**
     * The column <code>admin.t_faq_question.name</code>. Наименование
     */
    public final TableField<TFaqQuestionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "Наименование");

    /**
     * The column <code>admin.t_faq_question.question_type</code>. Тип вопроса
     */
    public final TableField<TFaqQuestionRecord, String> QUESTION_TYPE = createField(DSL.name("question_type"), SQLDataType.VARCHAR.nullable(false), this, "Тип вопроса");

    /**
     * The column <code>admin.t_faq_question.create_date</code>. Дата и время
     * создания
     */
    public final TableField<TFaqQuestionRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6), this, "Дата и время создания");

    /**
     * The column <code>admin.t_faq_question.create_user</code>. Автор создания
     */
    public final TableField<TFaqQuestionRecord, String> CREATE_USER = createField(DSL.name("create_user"), SQLDataType.VARCHAR(100), this, "Автор создания");

    /**
     * The column <code>admin.t_faq_question.last_update_date</code>. Дата и
     * время изменения
     */
    public final TableField<TFaqQuestionRecord, LocalDateTime> LAST_UPDATE_DATE = createField(DSL.name("last_update_date"), SQLDataType.LOCALDATETIME(6), this, "Дата и время изменения");

    /**
     * The column <code>admin.t_faq_question.last_update_user</code>. Автор
     * изменения
     */
    public final TableField<TFaqQuestionRecord, String> LAST_UPDATE_USER = createField(DSL.name("last_update_user"), SQLDataType.VARCHAR(100), this, "Автор изменения");

    private TFaqQuestion(Name alias, Table<TFaqQuestionRecord> aliased) {
        this(alias, aliased, null);
    }

    private TFaqQuestion(Name alias, Table<TFaqQuestionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("FAQ: вопросы"), TableOptions.table());
    }

    /**
     * Create an aliased <code>admin.t_faq_question</code> table reference
     */
    public TFaqQuestion(String alias) {
        this(DSL.name(alias), T_FAQ_QUESTION);
    }

    /**
     * Create an aliased <code>admin.t_faq_question</code> table reference
     */
    public TFaqQuestion(Name alias) {
        this(alias, T_FAQ_QUESTION);
    }

    /**
     * Create a <code>admin.t_faq_question</code> table reference
     */
    public TFaqQuestion() {
        this(DSL.name("t_faq_question"), null);
    }

    public <O extends Record> TFaqQuestion(Table<O> child, ForeignKey<O, TFaqQuestionRecord> key) {
        super(child, key, T_FAQ_QUESTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Admin.ADMIN;
    }

    @Override
    public UniqueKey<TFaqQuestionRecord> getPrimaryKey() {
        return Keys.T_FAQ_QUESTION_PK;
    }

    @Override
    public TFaqQuestion as(String alias) {
        return new TFaqQuestion(DSL.name(alias), this);
    }

    @Override
    public TFaqQuestion as(Name alias) {
        return new TFaqQuestion(alias, this);
    }

    @Override
    public TFaqQuestion as(Table<?> alias) {
        return new TFaqQuestion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TFaqQuestion rename(String name) {
        return new TFaqQuestion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TFaqQuestion rename(Name name) {
        return new TFaqQuestion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TFaqQuestion rename(Table<?> name) {
        return new TFaqQuestion(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
