/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import jooqdata.Admin;
import jooqdata.Keys;
import jooqdata.tables.records.TLetterTemplateVariableRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Переменные к шаблону письма
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TLetterTemplateVariable extends TableImpl<TLetterTemplateVariableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>admin.t_letter_template_variable</code>
     */
    public static final TLetterTemplateVariable T_LETTER_TEMPLATE_VARIABLE = new TLetterTemplateVariable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TLetterTemplateVariableRecord> getRecordType() {
        return TLetterTemplateVariableRecord.class;
    }

    /**
     * The column <code>admin.t_letter_template_variable.id</code>. Первичный
     * ключ
     */
    public final TableField<TLetterTemplateVariableRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("admin.get_id()", SQLDataType.BIGINT)), this, "Первичный ключ");

    /**
     * The column
     * <code>admin.t_letter_template_variable.letter_template_id</code>. Шаблон
     * письма
     */
    public final TableField<TLetterTemplateVariableRecord, Long> LETTER_TEMPLATE_ID = createField(DSL.name("letter_template_id"), SQLDataType.BIGINT.nullable(false), this, "Шаблон письма");

    /**
     * The column <code>admin.t_letter_template_variable.name</code>.
     * Переменная. Удалить!!!
     */
    public final TableField<TLetterTemplateVariableRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "Переменная. Удалить!!!");

    /**
     * The column <code>admin.t_letter_template_variable.val</code>.
     * Наименование переменной. Удалить!!!
     */
    public final TableField<TLetterTemplateVariableRecord, String> VAL = createField(DSL.name("val"), SQLDataType.VARCHAR, this, "Наименование переменной. Удалить!!!");

    /**
     * The column <code>admin.t_letter_template_variable.create_date</code>.
     * Дата и время создания
     */
    public final TableField<TLetterTemplateVariableRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6), this, "Дата и время создания");

    /**
     * The column <code>admin.t_letter_template_variable.create_user</code>.
     * Автор создания
     */
    public final TableField<TLetterTemplateVariableRecord, String> CREATE_USER = createField(DSL.name("create_user"), SQLDataType.VARCHAR(100), this, "Автор создания");

    /**
     * The column
     * <code>admin.t_letter_template_variable.last_update_date</code>. Дата и
     * время изменения
     */
    public final TableField<TLetterTemplateVariableRecord, LocalDateTime> LAST_UPDATE_DATE = createField(DSL.name("last_update_date"), SQLDataType.LOCALDATETIME(6), this, "Дата и время изменения");

    /**
     * The column
     * <code>admin.t_letter_template_variable.last_update_user</code>. Автор
     * изменения
     */
    public final TableField<TLetterTemplateVariableRecord, String> LAST_UPDATE_USER = createField(DSL.name("last_update_user"), SQLDataType.VARCHAR(100), this, "Автор изменения");

    /**
     * The column <code>admin.t_letter_template_variable.variable_id</code>.
     * Переменная
     */
    public final TableField<TLetterTemplateVariableRecord, Long> VARIABLE_ID = createField(DSL.name("variable_id"), SQLDataType.BIGINT, this, "Переменная");

    private TLetterTemplateVariable(Name alias, Table<TLetterTemplateVariableRecord> aliased) {
        this(alias, aliased, null);
    }

    private TLetterTemplateVariable(Name alias, Table<TLetterTemplateVariableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Переменные к шаблону письма"), TableOptions.table());
    }

    /**
     * Create an aliased <code>admin.t_letter_template_variable</code> table
     * reference
     */
    public TLetterTemplateVariable(String alias) {
        this(DSL.name(alias), T_LETTER_TEMPLATE_VARIABLE);
    }

    /**
     * Create an aliased <code>admin.t_letter_template_variable</code> table
     * reference
     */
    public TLetterTemplateVariable(Name alias) {
        this(alias, T_LETTER_TEMPLATE_VARIABLE);
    }

    /**
     * Create a <code>admin.t_letter_template_variable</code> table reference
     */
    public TLetterTemplateVariable() {
        this(DSL.name("t_letter_template_variable"), null);
    }

    public <O extends Record> TLetterTemplateVariable(Table<O> child, ForeignKey<O, TLetterTemplateVariableRecord> key) {
        super(child, key, T_LETTER_TEMPLATE_VARIABLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Admin.ADMIN;
    }

    @Override
    public UniqueKey<TLetterTemplateVariableRecord> getPrimaryKey() {
        return Keys.T_LETTER_TEMPLATE_VARIABLES_PK;
    }

    @Override
    public List<ForeignKey<TLetterTemplateVariableRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_LETTER_TEMPLATE_VARIABLE__T_LETTER_TEMPLATE_VARIABLE_FK1, Keys.T_LETTER_TEMPLATE_VARIABLE__T_LETTER_TEMPLATE_VARIABLE_FK2);
    }

    private transient TLetterTemplate _tLetterTemplate;
    private transient TVariable _tVariable;

    /**
     * Get the implicit join path to the <code>admin.t_letter_template</code>
     * table.
     */
    public TLetterTemplate tLetterTemplate() {
        if (_tLetterTemplate == null)
            _tLetterTemplate = new TLetterTemplate(this, Keys.T_LETTER_TEMPLATE_VARIABLE__T_LETTER_TEMPLATE_VARIABLE_FK1);

        return _tLetterTemplate;
    }

    /**
     * Get the implicit join path to the <code>admin.t_variable</code> table.
     */
    public TVariable tVariable() {
        if (_tVariable == null)
            _tVariable = new TVariable(this, Keys.T_LETTER_TEMPLATE_VARIABLE__T_LETTER_TEMPLATE_VARIABLE_FK2);

        return _tVariable;
    }

    @Override
    public TLetterTemplateVariable as(String alias) {
        return new TLetterTemplateVariable(DSL.name(alias), this);
    }

    @Override
    public TLetterTemplateVariable as(Name alias) {
        return new TLetterTemplateVariable(alias, this);
    }

    @Override
    public TLetterTemplateVariable as(Table<?> alias) {
        return new TLetterTemplateVariable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TLetterTemplateVariable rename(String name) {
        return new TLetterTemplateVariable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TLetterTemplateVariable rename(Name name) {
        return new TLetterTemplateVariable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TLetterTemplateVariable rename(Table<?> name) {
        return new TLetterTemplateVariable(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, LocalDateTime, String, LocalDateTime, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Long, ? super Long, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Long, ? super Long, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
