/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import jooqdata.Admin;
import jooqdata.Keys;
import jooqdata.tables.records.TVariableRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Переменная
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TVariable extends TableImpl<TVariableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>admin.t_variable</code>
     */
    public static final TVariable T_VARIABLE = new TVariable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TVariableRecord> getRecordType() {
        return TVariableRecord.class;
    }

    /**
     * The column <code>admin.t_variable.id</code>. Первичный ключ
     */
    public final TableField<TVariableRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("admin.get_id()", SQLDataType.BIGINT)), this, "Первичный ключ");

    /**
     * The column <code>admin.t_variable.name</code>. Наименование
     */
    public final TableField<TVariableRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "Наименование");

    /**
     * The column <code>admin.t_variable.description</code>. Описание
     */
    public final TableField<TVariableRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "Описание");

    /**
     * The column <code>admin.t_variable.default_val</code>. Значение по
     * умолчанию
     */
    public final TableField<TVariableRecord, String> DEFAULT_VAL = createField(DSL.name("default_val"), SQLDataType.VARCHAR, this, "Значение по умолчанию");

    /**
     * The column <code>admin.t_variable.create_date</code>. Дата и время
     * создания
     */
    public final TableField<TVariableRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), SQLDataType.LOCALDATETIME(6), this, "Дата и время создания");

    /**
     * The column <code>admin.t_variable.create_user</code>. Автор создания
     */
    public final TableField<TVariableRecord, String> CREATE_USER = createField(DSL.name("create_user"), SQLDataType.VARCHAR(100), this, "Автор создания");

    /**
     * The column <code>admin.t_variable.last_update_date</code>. Дата и время
     * изменения
     */
    public final TableField<TVariableRecord, LocalDateTime> LAST_UPDATE_DATE = createField(DSL.name("last_update_date"), SQLDataType.LOCALDATETIME(6), this, "Дата и время изменения");

    /**
     * The column <code>admin.t_variable.last_update_user</code>. Автор
     * изменения
     */
    public final TableField<TVariableRecord, String> LAST_UPDATE_USER = createField(DSL.name("last_update_user"), SQLDataType.VARCHAR(100), this, "Автор изменения");

    private TVariable(Name alias, Table<TVariableRecord> aliased) {
        this(alias, aliased, null);
    }

    private TVariable(Name alias, Table<TVariableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Переменная"), TableOptions.table());
    }

    /**
     * Create an aliased <code>admin.t_variable</code> table reference
     */
    public TVariable(String alias) {
        this(DSL.name(alias), T_VARIABLE);
    }

    /**
     * Create an aliased <code>admin.t_variable</code> table reference
     */
    public TVariable(Name alias) {
        this(alias, T_VARIABLE);
    }

    /**
     * Create a <code>admin.t_variable</code> table reference
     */
    public TVariable() {
        this(DSL.name("t_variable"), null);
    }

    public <O extends Record> TVariable(Table<O> child, ForeignKey<O, TVariableRecord> key) {
        super(child, key, T_VARIABLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Admin.ADMIN;
    }

    @Override
    public UniqueKey<TVariableRecord> getPrimaryKey() {
        return Keys.T_VARIABLE_PK;
    }

    @Override
    public TVariable as(String alias) {
        return new TVariable(DSL.name(alias), this);
    }

    @Override
    public TVariable as(Name alias) {
        return new TVariable(alias, this);
    }

    @Override
    public TVariable as(Table<?> alias) {
        return new TVariable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TVariable rename(String name) {
        return new TVariable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVariable rename(Name name) {
        return new TVariable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TVariable rename(Table<?> name) {
        return new TVariable(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
