## Set docker registry location
ARG QUAYIO_IMAGE_REPOSITORY=quay-registry.dso.techpark.local
ARG RH_IMAGE_REPOSITORY=rh-registry.dso.techpark.local
ARG UBI9_REPO_URL=""
ARG UBI9_REPO_URL_CA=""
ARG UBI9_REPO_URL_SUB_CA=""
## Set maven registry
ARG MAVEN_REPOSITORY=https://nexus.dso.techpark.local/repository/maven2-gradle-external-dso
ARG MAVEN_REPOSITORY_PLUGIN=https://nexus.dso.techpark.local/repository/maven2-gradle-external-dso
## Set optional maven registry certificates
ARG MAVEN_REPOSITORY_ROOT_CA_URL=https://nexus.dso.techpark.local/repository/local-repo/CA/root-ca-gazprom-neft.pem
ARG MAVEN_REPOSITORY_SUB_CA_URL=https://nexus.dso.techpark.local/repository/local-repo/CA/sub-ca.pem
## Set application build path
ARG BUILD_APP_DIR='/application'

#
FROM  $QUAYIO_IMAGE_REPOSITORY/klovercloud/gradle:7.6.0-jdk17 as build

ARG BUILD_APP_DIR
ARG MAVEN_REPOSITORY
ARG MAVEN_REPOSITORY_PLUGIN
ARG MAVEN_REPOSITORY_ROOT_CA_URL
ARG MAVEN_REPOSITORY_SUB_CA_URL

ENV TZ Europe/Moscow
WORKDIR $BUILD_APP_DIR
COPY . .

ENV GRADLE_USER_HOME=$BUILD_APP_DIR/gradle

## Add certificate
RUN JKS_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1) \
    && if [ -n "$MAVEN_REPOSITORY_ROOT_CA_URL" ]; then wget --no-check-certificate -q -O - $MAVEN_REPOSITORY_ROOT_CA_URL > ./root-ca-maven.crt \
    && keytool -import -noprompt -alias root -file ./root-ca-maven.crt -keystore ./maven.jks -storepass $JKS_KEY; fi \
    && if [ -n "$MAVEN_REPOSITORY_SUB_CA_URL" ]; then wget --no-check-certificate -q -O - $MAVEN_REPOSITORY_SUB_CA_URL > ./sub-ca-maven.crt \
    && keytool -import -noprompt -alias sub -file ./sub-ca-maven.crt -keystore ./maven.jks -storepass $JKS_KEY; fi \
    && gradle build --init-script init.gradle -PmavenRepository=$MAVEN_REPOSITORY \
    -PmavenRepositoryPlugin=$MAVEN_REPOSITORY_PLUGIN -Djavax.net.ssl.trustStore="/application/maven.jks" -Djavax.net.ssl.trustStorePassword=$JKS_KEY

RUN java -Djarmode=layertools -jar $BUILD_APP_DIR/build/libs/root.jar extract
#
FROM  $RH_IMAGE_REPOSITORY/ubi9/openjdk-17-runtime:1.17-1.1705573249
ARG BUILD_APP_DIR
ARG UID=1001
ARG UBI9_REPO_URL
ARG UBI9_REPO_URL_CA
ARG UBI9_REPO_URL_SUB_CA

ENV TZ Europe/Moscow

USER root
# update Important packages
RUN if [ -n "$UBI9_REPO_URL" ]; then \
       curl -k -s $UBI9_REPO_URL_CA --output /etc/pki/ca-trust/source/anchors/root-ca-gazprom-neft.pem; \
       curl -k -s $UBI9_REPO_URL_SUB_CA --output /etc/pki/ca-trust/source/anchors/sub-ca-gazprom-neft.pem; \
       update-ca-trust; \
       rm -rf /etc/yum.repos.d/ubi.repo; \
       curl -k $UBI9_REPO_URL --output /etc/yum.repos.d/ubi.repo; \
    fi; \
    microdnf --setopt=tsflags=nodocs install -y \
        openssl-libs-3.0.7-25.el9_3 python3-3.9.18-1.el9_3.1 \
        rpm-4.16.1.3-27.el9_3 gnutls-3.7.6-23.el9_3.3 sqlite-libs-3.34.1-7.el9_3 \
        nspr-4.35.0-6.el9_3 nss-3.90.0-6.el9_3 nss-softokn-3.90.0-6.el9_3 && \
    microdnf clean all && \
    rm -rf /var/cache/yum

# Set permissions so that the container runs without root access
USER 0
RUN mkdir -p ${BUILD_APP_DIR}
RUN chown -R $UID:0 ${BUILD_APP_DIR}
USER $UID

WORKDIR $BUILD_APP_DIR

COPY --chown=$UID:0 ./docker/entrypoint.sh /
RUN chmod a+x /entrypoint.sh

COPY --chown=$UID:0 --from=build $BUILD_APP_DIR/dependencies/ ./
COPY --chown=$UID:0 --from=build $BUILD_APP_DIR/spring-boot-loader/ ./
COPY --chown=$UID:0 --from=build $BUILD_APP_DIR/snapshot-dependencies/ ./
COPY --chown=$UID:0 --from=build $BUILD_APP_DIR/application/ ./

## Set application runtime path
ENV RUNTIME_PATH='/tmp'

VOLUME ["$RUNTIME_PATH"]

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT ["/entrypoint.sh"]
CMD ["org.springframework.boot.loader.launch.JarLauncher"]
