application:
  env:
    configmap:
      - key: DB_SCHEMA
        value: admin
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: MIRROR_ENDPOINT_MA
        value: http://service-app-ma.tzriu:8080
      - key: MIRROR_ENDPOINT_RBAC
        value: http://service-app-rbac.tzriu:8080
      - key: MIRROR_KEYCLOAK_BASE_URL
        value: http://localhost
      - key: MIRROR_KEYCLOAK_REALM
        value: U200004739
      - key: MIRROR_KEYCLOAK_CLIENT_ID
        value: tzriu-mrp
    secret:
      - key: MIRROR_DATASOURCE_URL
        secretName: mirror-pg-cred
        secretKey: url
      - key: SPRING_DATASOURCE_USERNAME
        secretName: mirror-pg-cred
        secretKey: username
      - key: SPRING_DATASOURCE_PASSWORD
        secretName: mirror-pg-cred
        secretKey: password
      - key: MIRROR_KEYCLOAK_CLIENT_SECRET
        secretName: mirror-sso-confid-cred
        secretKey: secret
      - key: MIRROR_SCHEDULE_TASKS_USERNAME
        secretName: mirror-sched-tasks-cred
        secretKey: username
      - key: MIRROR_SCHEDULE_TASKS_PASSWORD
        secretName: mirror-sched-tasks-cred
        secretKey: password

fullnameOverride: "service-app-admin"

resources:
  limits:
    cpu: 400m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

prometheus:
  monitoring:
    enabled: true
