application:
  env:
    configmap:
      - key: DB_SCHEMA
        value: admin
      - key: SPRING_PROFILES_ACTIVE
        value: trust
      - key: MIRROR_DATASOURCE_URL
        value: "jdbc:postgresql://10.50.54.219:5432/mirror"
      - key: MIRROR_ENDPOINT_PY_ES_DATA_MGMT
        value: http://service-py-es-data-mgmt.tzriu:8080
      - key: MIRROR_ENDPOINT_MA
        value: http://service-app-ma.tzriu:8080
      - key: MIRROR_ENDPOINT_RBAC
        value: http://service-app-rbac.tzriu:8080
      - key: MIRROR_ENDPOINT_INTEGRATION
        value: http://service-app-integration.tzriu:8080
      - key: MIRROR_ENDPOINT_DOC
        value: http://service-app-doc.tzriu:8080
      - key: MIRROR_ENDPOINT_EP
        value: http://service-app-ep.tzriu:8080
      - key: MIRROR_ENDPOINT_NSI
        value: http://service-app-nsi.tzriu:8080
      - key: MIRROR_ENDPOINT_PRCAT
        value: http://service-app-prcat.tzriu:8080
      - key: MIRROR_ENDPOINT_REPORT
        value: http://service-app-report.tzriu:8080
      - key: MIRROR_ENDPOINT_CHAT
        value: http://service-app-chat.tzriu:8080
      - key: MIRROR_ENDPOINT_USER_PROFILE
        value: http://service-app-userprofile.tzriu:8080
      - key: MIRROR_ENDPOINT_NOTIFICATION
        value: http://service-app-notification.tzriu:8080
      - key: MIRROR_KEYCLOAK_BASE_URL
        value: https://sso-apps-745.apps.test.gazprom-neft.local/auth
      - key: MIRROR_KEYCLOAK_REALM
        value: U200004739
      - key: MIRROR_KEYCLOAK_CLIENT_ID
        value: tzriu-mrp
      - key: KEYCLOAK_ROOT_CA_URL
        value: https://nexus.gazprom-neft.local/repository/local-repo/CA/root-ca-gazprom-neft.pem
      - key: KEYCLOAK_SUB_CA_URL
        value: https://nexus.gazprom-neft.local/repository/local-repo/CA/sub-ca.pem
      - key: MIRROR_SCHEDULE_TASKS_CRON_REPLICATE_PROCEDURE_RECORDS
        value: 0 0 1 20 * ?
      - key: MIRROR_SCHEDULE_TASKS_CRON_SAVE_SEARCH_HISTORY
        value: 0 30 23 * * *
      - key: MIRROR_SCHEDULE_TASKS_CRON_NOTIFY_OFFER_END
        value: 0 0 9 * * *
      - key: MIRROR_SCHEDULE_TASKS_CRON_CHANGE_STATUS_OFFER_END
        value: 0 1 0 * * *
      - key: MIRROR_SCHEDULE_TASKS_CRON_NOTIFICATION_PROCESS
        value: 0 0 1 * * *
      - key: MIRROR_SCHEDULE_TASKS_CRON_DAILY_INTEGRATION_UPLOADING
        value: 0 0 5 * * *
      - key: MIRROR_LDAP_URL
        value: ldap://SPB99-DC01.gazprom-neft.local
      - key: MIRROR_LDAP_BASE
        value: DC=gazprom-neft,DC=local
      - key: MIRROR_LDAP_FILTER
        value: "CN=SPB-SSO-ALLUSERS-U200004739,OU=U200004739,OU=Groups,OU=ПАО Газпром нефть,OU=SPB,OU=Regions,DC=gazprom-neft,DC=local"
      - key: MIRROR_LDAP_SVC_USERS
        value: SPB-SSO-U200004739,mirror-uat-postgr,mirror-prod-postgr,mirror-mailbox-uat,mirror-mailbox,mirror-uat-tpartner,mirror-prod-tpartner,mirror-uat-bground,mirror-prod-bground,mirror-uat-techasuz,mirror-prod-techasuz,SPB-KLAD-D-tzriu2-M,SPB-KLAD-P-tzriu2-R
      - key: MIRROR_KVP
        value: false
    secret:
      - key: SPRING_DATASOURCE_USERNAME
        secretName: mirror-pg-cred
        secretKey: username
      - key: SPRING_DATASOURCE_PASSWORD
        secretName: mirror-pg-cred
        secretKey: password
      - key: MIRROR_KEYCLOAK_CLIENT_SECRET
        secretName: mirror-sso-confid-cred
        secretKey: secret
      - key: MIRROR_SCHEDULE_TASKS_USERNAME
        secretName: mirror-sched-tasks-cred
        secretKey: username
      - key: MIRROR_SCHEDULE_TASKS_PASSWORD
        secretName: mirror-sched-tasks-cred
        secretKey: password
      - key: MIRROR_LDAP_USERNAME
        secretName: mirror-ldap-cred
        secretKey: username
      - key: MIRROR_LDAP_PASSWORD
        secretName: mirror-ldap-cred
        secretKey: password

fullnameOverride: "service-app-admin"

service:
  managementPort: 8081

resources:
  limits:
    cpu: 400m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

prometheus:
  monitoring:
    enabled: true
