# Default values for tzriu-be-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: nexus-registry.inlinegroup-c.ru/tzriu/service-app-admin

application:
  env:
    configmap:
      - key: DB_SCHEMA
        value: admin
      - key: SPRING_PROFILES_ACTIVE
        value: release
      - key: MIRROR_DATASOURCE_URL
        value: "jdbc:postgresql://igcs0009.inlinegroup-c.ru:5432/mirror_release"
      - key: MIRROR_ENDPOINT_PY_ES_DATA_MGMT
        value: http://service-py-es-data-mgmt.mirror-release:8080
      - key: MIRROR_ENDPOINT_MA
        value: http://service-app-ma.mirror-release:8080
      - key: MIRROR_ENDPOINT_RBAC
        value: http://service-app-rbac.mirror-release:8080
      - key: MIRROR_ENDPOINT_INTEGRATION
        value: http://service-app-integration.mirror-release:8080
      - key: MIRROR_ENDPOINT_DOC
        value: http://service-app-doc.mirror-release:8080
      - key: MIRROR_ENDPOINT_EP
        value: http://service-app-ep.mirror-release:8080
      - key: MIRROR_ENDPOINT_NSI
        value: http://service-app-nsi.mirror-release:8080
      - key: MIRROR_ENDPOINT_PRCAT
        value: http://service-app-prcat.mirror-release:8080
      - key: MIRROR_ENDPOINT_REPORT
        value: http://service-app-report.mirror-release:8080
      - key: MIRROR_ENDPOINT_CHAT
        value: http://service-app-chat.mirror-release:8080
      - key: MIRROR_ENDPOINT_USER_PROFILE
        value: http://service-app-userprofile.mirror-release:8080
      - key: MIRROR_ENDPOINT_NOTIFICATION
        value: http://service-app-notification.mirror-release:8080
      - key: MIRROR_KEYCLOAK_BASE_URL
        value: https://keycloak-dev.inlinegroup-c.ru
      - key: MIRROR_KEYCLOAK_REALM
        value: mirror_test
      - key: MIRROR_KEYCLOAK_CLIENT_ID
        value: mirror-integration-app
      - key: KEYCLOAK_ROOT_CA_URL
        value: https://nexus-oss.inlinegroup-c.ru/repository/local-repo/CA/root.x1.pem
      - key: KEYCLOAK_SUB_CA_URL
        value: https://nexus-oss.inlinegroup-c.ru/repository/local-repo/CA/r3.pem
      - key: MIRROR_SCHEDULE_TASKS_CRON_REPLICATE_PROCEDURE_RECORDS
        value: 0 0 1 20 * ?
      - key: MIRROR_SCHEDULE_TASKS_CRON_SAVE_SEARCH_HISTORY
        value: 0 30 23 * * *
      - key: MIRROR_SCHEDULE_TASKS_CRON_NOTIFY_OFFER_END
        value: 0 0 9 * * *
      - key: MIRROR_SCHEDULE_TASKS_CRON_CHANGE_STATUS_OFFER_END
        value: 0 1 0 * * *
      - key: MIRROR_SCHEDULE_TASKS_CRON_NOTIFICATION_PROCESS
        value: 0 0 1 * * *
      - key: MIRROR_SCHEDULE_TASKS_CRON_DAILY_INTEGRATION_UPLOADING
        value: 0 0 5 * * *
      - key: MIRROR_LDAP_URL
        value: ldap://samba-ad-dh.inlinegroup-c.ru
      - key: MIRROR_LDAP_BASE
        value: CN=Users,DC=inlinegroup-c,DC=ru
      - key: MIRROR_LDAP_FILTER
        value: CN=SPB-SSO-ALLUSERS,CN=Users,DC=inlinegroup-c,DC=ru
      - key: MIRROR_LDAP_SVC_USERS
        value: mirror_async,mirror_sched,mirror_integration,mirror-tpartner
    secret:
      - key: SPRING_DATASOURCE_USERNAME
        secretName: mirror-pg-cred
        secretKey: username
      - key: SPRING_DATASOURCE_PASSWORD
        secretName: mirror-pg-cred
        secretKey: password
      - key: MIRROR_KEYCLOAK_CLIENT_SECRET
        secretName: mirror-sso-confid-cred
        secretKey: secret
      - key: MIRROR_SCHEDULE_TASKS_USERNAME
        secretName: mirror-sched-tasks-cred
        secretKey: username
      - key: MIRROR_SCHEDULE_TASKS_PASSWORD
        secretName: mirror-sched-tasks-cred
        secretKey: password
      - key: MIRROR_LDAP_USERNAME
        secretName: mirror-ldap-cred
        secretKey: username
      - key: MIRROR_LDAP_PASSWORD
        secretName: mirror-ldap-cred
        secretKey: password

imagePullSecrets:
  - name: nexus-credential

fullnameOverride: "service-app-admin"

service:
  managementPort: 8081

ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: intersigned
  hosts:
    - host: mirror-release.inlinegroup-c.ru
      paths:
        - path: /api/admin/?(.*)
          pathType: Prefix
  tls:
    - secretName: mirror-release-tls
      hosts:
        - mirror-release.inlinegroup-c.ru

resources:
  limits:
    cpu: 400m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

prometheus:
  monitoring:
    enabled: true
