# Default values for tzriu-be-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: nexus-registry.inlinegroup-c.ru/tzriu/service-app-admin

application:
  env:
    configmap:
      - key: DB_SCHEMA
        value: admin
      - key: SPRING_PROFILES_ACTIVE
        value: trunk
      - key: MIRROR_ENDPOINT_MA
        value: http://service-app-ma.mirror:8080
      - key: MIRROR_ENDPOINT_RBAC
        value: http://service-app-rbac.mirror:8080
      - key: KEYCLOAK_JWK_SET_URI
        value: https://keycloak.inlinegroup-c.ru/realms/mirror_test/protocol/openid-connect/certs
    secret:
      - key: MIRROR_DATASOURCE_URL
        secretName: mirror-pg-cred
        secretKey: url
      - key: SPRING_DATASOURCE_USERNAME
        secretName: mirror-pg-cred
        secretKey: username
      - key: SPRING_DATASOURCE_PASSWORD
        secretName: mirror-pg-cred
        secretKey: password
      - key: MIRROR_SCHEDULE_TASKS_USERNAME
        secretName: mirror-sched-tasks-cred
        secretKey: username
      - key: MIRROR_SCHEDULE_TASKS_PASSWORD
        secretName: mirror-sched-tasks-cred
        secretKey: password

imagePullSecrets:
  - name: nexus-credential

fullnameOverride: "service-app-admin"

ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: mirror.inlinegroup-c.ru
      paths:
        - path: /api/admin/?(.*)
          pathType: Prefix

resources:
  limits:
    cpu: 600m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

prometheus:
  monitoring:
    enabled: true
