# Default values for tzriu-be-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: nexus-registry.inlinegroup-c.ru/tzriu/service-app-admin

application:
  env:
    configmap:
      - key: DB_SCHEMA
        value: admin
      - key: SPRING_PROFILES_ACTIVE
        value: trunk
      - key: MIRROR_ENDPOINT_MA
        value: http://service-app-ma.mirror-release:8080
      - key: MIRROR_ENDPOINT_RBAC
        value: http://service-app-rbac.mirror-release:8080
      - key: MIRROR_ENDPOINT_INTEGRATION
        value: http://service-app-integration.mirror-release:8080
      - key: MIRROR_ENDPOINT_DOC
        value: http://service-app-doc.mirror-release:8080
      - key: MIRROR_KEYCLOAK_BASE_URL
        value: https://keycloak.inlinegroup-c.ru
      - key: MIRROR_KEYCLOAK_REALM
        value: mirror_test
      - key: MIRROR_KEYCLOAK_CLIENT_ID
        value: mirror-integration-app
      - key: KEYCLOAK_ROOT_CA_URL
        value: https://nexus-oss.inlinegroup-c.ru/repository/local-repo/CA/root.ca.pem
#      - key: KEYCLOAK_SUB_CA_URL
#        value: ""
      - key: MIRROR_SCHEDULE_TASKS_CRON_REPLICATE_PROCEDURE_RECORDS
        value: 0 0 1 4 * ?
      - key: MIRROR_SCHEDULE_TASKS_CRON_SAVE_SEARCH_HISTORY
        value: 0 30 23 * * *
    secret:
      - key: MIRROR_DATASOURCE_URL
        secretName: mirror-pg-cred
        secretKey: url
      - key: SPRING_DATASOURCE_USERNAME
        secretName: mirror-pg-cred
        secretKey: username
      - key: SPRING_DATASOURCE_PASSWORD
        secretName: mirror-pg-cred
        secretKey: password
      - key: MIRROR_KEYCLOAK_CLIENT_SECRET
        secretName: mirror-sso-confid-cred
        secretKey: secret
      - key: MIRROR_SCHEDULE_TASKS_USERNAME
        secretName: mirror-sched-tasks-cred
        secretKey: username
      - key: MIRROR_SCHEDULE_TASKS_PASSWORD
        secretName: mirror-sched-tasks-cred
        secretKey: password

imagePullSecrets:
  - name: nexus-credential

fullnameOverride: "service-app-admin"

service:
  managementPort: 8081

ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: mirror-release.inlinegroup-c.ru
      paths:
        - path: /api/admin/?(.*)
          pathType: Prefix

resources:
  limits:
    cpu: 400m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

prometheus:
  monitoring:
    enabled: true
