variables:
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1
  ACTIVE_PROFILE: "trunk"
  APPLICATION_VERSION: "0.1.$CI_PIPELINE_IID"
  APPLICATION_NAME: service-app-admin
#  DEPLOY_BRANCH: develop-local
  DEPLOY_BRANCH: task/stronini
  CHART_NAME: tzriu-be-spring
  KUBERNETES_NAMESPACE_OVERWRITE: mirror
  IMAGE_REPOSITORY: nexus-registry.inlinegroup-c.ru/tzriu/$APPLICATION_NAME
  ENVIRONMENT_NAME: $ACTIVE_PROFILE

stages:
  - build
  - deploy

include:
  - local: ci/trunk/build.yml
  - local: ci/trunk/deploy.yml
