build:
  stage: build
  environment:
    name: $ENVIRONMENT_NAME
    action: prepare
  image:
    name: registry.inlinegroup-c.ru/tools/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cat $NEXUS_REGISTRY_CRED > /kaniko/.docker/config.json
    - cat $MIRROR_CA_PEM > ${CI_PROJECT_DIR}/root.ca.pem
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile-trunk"
      --destination "${IMAGE_REPOSITORY}:${APPLICATION_VERSION}"
  rules:
    - if: $CI_COMMIT_BRANCH == $DEPLOY_BRANCH