/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import java.util.Arrays;
import java.util.List;

import jooqdata.tables.AParam;
import jooqdata.tables.TLetterTemplate;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Admin extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>admin</code>
     */
    public static final Admin ADMIN = new Admin();

    /**
     * Ведение параметров приложения
     */
    public final AParam A_PARAM = AParam.A_PARAM;

    /**
     * Шаблон письма
     */
    public final TLetterTemplate T_LETTER_TEMPLATE = TLetterTemplate.T_LETTER_TEMPLATE;

    /**
     * No further instances allowed
     */
    private Admin() {
        super("admin", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.GLOBAL_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AParam.A_PARAM,
            TLetterTemplate.T_LETTER_TEMPLATE
        );
    }
}
