/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.TExternalSource;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in admin.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_EXTERNAL_SOURCE_CODE_IDX = Internal.createIndex(DSL.name("t_external_source_code_idx"), TExternalSource.T_EXTERNAL_SOURCE, new OrderField[] { TExternalSource.T_EXTERNAL_SOURCE.CODE }, true);
}
