/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.TServiceOfferType;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in admin.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_SERVICE_OFFER_TYPE_SERVICE_CODE_IDX = Internal.createIndex(DSL.name("t_service_offer_type_service_code_idx"), TServiceOfferType.T_SERVICE_OFFER_TYPE, new OrderField[] { TServiceOfferType.T_SERVICE_OFFER_TYPE.SERVICE_CODE }, true);
}
