/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.routines.GetId;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in admin.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>admin.get_id</code>
     */
    public static Long getId(
          Configuration configuration
    ) {
        GetId f = new GetId();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>admin.get_id</code> as a field.
     */
    public static Field<Long> getId() {
        GetId f = new GetId();

        return f.asField();
    }
}
