/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.AParam;
import jooqdata.tables.TLetterTemplate;


/**
 * Convenience access to all tables in admin.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Ведение параметров приложения
     */
    public static final AParam A_PARAM = AParam.A_PARAM;

    /**
     * Шаблон письма
     */
    public static final TLetterTemplate T_LETTER_TEMPLATE = TLetterTemplate.T_LETTER_TEMPLATE;
}
