/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.AParam;
import jooqdata.tables.TAnswerVersion;
import jooqdata.tables.TCalendarProduction;
import jooqdata.tables.TLetterTemplate;
import jooqdata.tables.TLetterTemplateAcceptableDocumentFormatEnum;
import jooqdata.tables.TLetterTemplateTypeTemplateEnum;
import jooqdata.tables.TLetterTemplateVariable;
import jooqdata.tables.TQuestion;
import jooqdata.tables.TServiceOfferType;
import jooqdata.tables.TVariable;


/**
 * Convenience access to all tables in admin.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Ведение параметров приложения
     */
    public static final AParam A_PARAM = AParam.A_PARAM;

    /**
     * Вариант ответа на вопрос
     */
    public static final TAnswerVersion T_ANSWER_VERSION = TAnswerVersion.T_ANSWER_VERSION;

    /**
     * Производственный календарь
     */
    public static final TCalendarProduction T_CALENDAR_PRODUCTION = TCalendarProduction.T_CALENDAR_PRODUCTION;

    /**
     * Шаблон письма
     */
    public static final TLetterTemplate T_LETTER_TEMPLATE = TLetterTemplate.T_LETTER_TEMPLATE;

    /**
     * Допустимый формат документа (Enum)
     */
    public static final TLetterTemplateAcceptableDocumentFormatEnum T_LETTER_TEMPLATE_ACCEPTABLE_DOCUMENT_FORMAT_ENUM = TLetterTemplateAcceptableDocumentFormatEnum.T_LETTER_TEMPLATE_ACCEPTABLE_DOCUMENT_FORMAT_ENUM;

    /**
     * Вид шаблона (Enum)
     */
    public static final TLetterTemplateTypeTemplateEnum T_LETTER_TEMPLATE_TYPE_TEMPLATE_ENUM = TLetterTemplateTypeTemplateEnum.T_LETTER_TEMPLATE_TYPE_TEMPLATE_ENUM;

    /**
     * Переменные к шаблону письма
     */
    public static final TLetterTemplateVariable T_LETTER_TEMPLATE_VARIABLE = TLetterTemplateVariable.T_LETTER_TEMPLATE_VARIABLE;

    /**
     * Преднастроенный вопрос
     */
    public static final TQuestion T_QUESTION = TQuestion.T_QUESTION;

    /**
     * Вид шаблона КП для услуги
     */
    public static final TServiceOfferType T_SERVICE_OFFER_TYPE = TServiceOfferType.T_SERVICE_OFFER_TYPE;

    /**
     * Переменная
     */
    public static final TVariable T_VARIABLE = TVariable.T_VARIABLE;
}
